services:
  db:
    image: postgres:15
    container_name: practica789_postgres
    environment:
      POSTGRES_DB: practica789
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
